// <auto-generated />
using System;
using ImpactSupport.Api.Support.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ImpactSupport.Api.Migrations
{
    [DbContext(typeof(SupportDbContext))]
    [Migration("20260815033244_InitialSupportChatSqlite")]
    partial class InitialSupportChatSqlite
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("ImpactSupport.Api.Support.Data.SupportMessage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("MessageId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MessageText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MessageType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SenderName")
                        .HasColumnType("TEXT");

                    b.Property<string>("SenderRole")
                        .HasColumnType("TEXT");

                    b.Property<string>("SenderUserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SupportSessionId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MessageId")
                        .IsUnique();

                    b.HasIndex("SupportSessionId");

                    b.ToTable("SupportMessages");
                });

            modelBuilder.Entity("ImpactSupport.Api.Support.Data.SupportSession", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClientName")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ClosedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("CurrentUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("DocumentId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DocumentLink")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImpactSessionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ModuleName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SupportSessionId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TicketNo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UserName")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserRole")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SupportSessionId")
                        .IsUnique();

                    b.HasIndex("TicketNo")
                        .IsUnique();

                    b.HasIndex("UserId", "DocumentId", "UserRole", "Status");

                    b.ToTable("SupportSessions");
                });

            modelBuilder.Entity("ImpactSupport.Api.TestCaseViewer.Data.QaDashboardFileCache", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("DriveModifiedTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("FileId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FolderUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("LastDriveCheckedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("LastGoogleUpdateAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("LastLocalSyncAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("LastMetadataSyncedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("LastScannedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("LocalTsvPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PendingEditCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ReportType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ScanError")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ScanStatus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SyncError")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SyncStatus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ReportType", "FileId")
                        .IsUnique();

                    b.ToTable("QaDashboardFileCaches");
                });

            modelBuilder.Entity("ImpactSupport.Api.TestCaseViewer.Data.QaDashboardSheetCache", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DevRemarks")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DevStatus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("DriveModifiedTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("FailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FileCacheId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FileId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("FixedCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FutureDevelopmentCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LastGoogleUpdateAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("LastLocalSyncAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("LastMetadataSyncedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("LastRefreshedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Link")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LocalTsvPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Module")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("NotClearCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NotReplicateCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PassCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PendingEditCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PostponedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PurposeOfTesting")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RefreshError")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RefreshStatus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RejectedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Remarks")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RowsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("SheetGid")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SheetIndex")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SheetLink")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SheetName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SyncError")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SyncStatus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalTestCases")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WipCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("FileCacheId");

                    b.HasIndex("FileId", "SheetName")
                        .IsUnique();

                    b.ToTable("QaDashboardSheetCaches");
                });

            modelBuilder.Entity("ImpactSupport.Api.TestCaseViewer.Data.QaImportBatch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("CommittedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("ExistingSheets")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("NewSheets")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ResultMode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RowsAdded")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RowsError")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RowsSkipped")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RowsUpdated")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SheetsDetected")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UploadKind")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UploadedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("UploadedBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UploadKind", "Status");

                    b.ToTable("QaImportBatches");
                });

            modelBuilder.Entity("ImpactSupport.Api.TestCaseViewer.Data.QaImportBatchError", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ErrorMessage")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ImportBatchId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RawValue")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RowNumber")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ImportBatchId");

                    b.ToTable("QaImportBatchErrors");
                });

            modelBuilder.Entity("ImpactSupport.Api.TestCaseViewer.Data.QaImportBatchRow", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ImportBatchId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ImportBatchSheetId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RowJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SourceRowNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TestCaseId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ImportBatchSheetId");

                    b.HasIndex("ImportBatchId", "TestCaseId")
                        .IsUnique();

                    b.ToTable("QaImportBatchRows");
                });

            modelBuilder.Entity("ImpactSupport.Api.TestCaseViewer.Data.QaImportBatchSheet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConflictStatus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ImportBatchId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ModuleName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedSheetName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RowCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SelectedAction")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SheetName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ImportBatchId", "NormalizedSheetName")
                        .IsUnique();

                    b.ToTable("QaImportBatchSheets");
                });

            modelBuilder.Entity("ImpactSupport.Api.TestCaseViewer.Data.TestCaseViewerUser", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MongoId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MongoId")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("TestCaseViewerUsers");
                });

            modelBuilder.Entity("ImpactSupport.Api.Support.Data.SupportMessage", b =>
                {
                    b.HasOne("ImpactSupport.Api.Support.Data.SupportSession", "SupportSession")
                        .WithMany("Messages")
                        .HasForeignKey("SupportSessionId")
                        .HasPrincipalKey("SupportSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SupportSession");
                });

            modelBuilder.Entity("ImpactSupport.Api.TestCaseViewer.Data.QaDashboardSheetCache", b =>
                {
                    b.HasOne("ImpactSupport.Api.TestCaseViewer.Data.QaDashboardFileCache", "FileCache")
                        .WithMany("Sheets")
                        .HasForeignKey("FileCacheId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FileCache");
                });

            modelBuilder.Entity("ImpactSupport.Api.TestCaseViewer.Data.QaImportBatchError", b =>
                {
                    b.HasOne("ImpactSupport.Api.TestCaseViewer.Data.QaImportBatch", "ImportBatch")
                        .WithMany("Errors")
                        .HasForeignKey("ImportBatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ImportBatch");
                });

            modelBuilder.Entity("ImpactSupport.Api.TestCaseViewer.Data.QaImportBatchRow", b =>
                {
                    b.HasOne("ImpactSupport.Api.TestCaseViewer.Data.QaImportBatch", "ImportBatch")
                        .WithMany("Rows")
                        .HasForeignKey("ImportBatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ImpactSupport.Api.TestCaseViewer.Data.QaImportBatchSheet", "ImportBatchSheet")
                        .WithMany("Rows")
                        .HasForeignKey("ImportBatchSheetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ImportBatch");

                    b.Navigation("ImportBatchSheet");
                });

            modelBuilder.Entity("ImpactSupport.Api.TestCaseViewer.Data.QaImportBatchSheet", b =>
                {
                    b.HasOne("ImpactSupport.Api.TestCaseViewer.Data.QaImportBatch", "ImportBatch")
                        .WithMany("Sheets")
                        .HasForeignKey("ImportBatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ImportBatch");
                });

            modelBuilder.Entity("ImpactSupport.Api.Support.Data.SupportSession", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("ImpactSupport.Api.TestCaseViewer.Data.QaDashboardFileCache", b =>
                {
                    b.Navigation("Sheets");
                });

            modelBuilder.Entity("ImpactSupport.Api.TestCaseViewer.Data.QaImportBatch", b =>
                {
                    b.Navigation("Errors");

                    b.Navigation("Rows");

                    b.Navigation("Sheets");
                });

            modelBuilder.Entity("ImpactSupport.Api.TestCaseViewer.Data.QaImportBatchSheet", b =>
                {
                    b.Navigation("Rows");
                });
#pragma warning restore 612, 618
        }
    }
}
