// <auto-generated />
using System;
using ImpactSupport.Api.Support.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ImpactSupport.Api.Migrations
{
    [DbContext(typeof(SupportDbContext))]
    [Migration("20260817035437_InitialSupportChatSqlite")]
    partial class InitialSupportChatSqlite
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("ImpactSupport.Api.Support.Data.SupportMessage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("MessageId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MessageText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MessageType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SenderName")
                        .HasColumnType("TEXT");

                    b.Property<string>("SenderRole")
                        .HasColumnType("TEXT");

                    b.Property<string>("SenderUserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SupportSessionId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MessageId")
                        .IsUnique();

                    b.HasIndex("SupportSessionId");

                    b.ToTable("SupportMessages");
                });

            modelBuilder.Entity("ImpactSupport.Api.Support.Data.SupportSession", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClientName")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ClosedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("CurrentUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("DocumentId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DocumentLink")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImpactSessionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ModuleName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SupportSessionId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TicketNo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UserName")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserRole")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SupportSessionId")
                        .IsUnique();

                    b.HasIndex("TicketNo")
                        .IsUnique();

                    b.HasIndex("UserId", "DocumentId", "UserRole", "Status");

                    b.ToTable("SupportSessions");
                });

            modelBuilder.Entity("ImpactSupport.Api.TestCaseViewer.Data.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Clients", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "OSO",
                            Name = "OSO"
                        },
                        new
                        {
                            Id = 2,
                            Code = "OXMEDO",
                            Name = "OxfordMed"
                        },
                        new
                        {
                            Id = 3,
                            Code = "TNF",
                            Name = "T & F"
                        },
                        new
                        {
                            Id = 4,
                            Code = "OUP",
                            Name = "OUP"
                        },
                        new
                        {
                            Id = 5,
                            Code = "LWW",
                            Name = "LWW"
                        },
                        new
                        {
                            Id = 6,
                            Code = "OHO",
                            Name = "OHO"
                        },
                        new
                        {
                            Id = 7,
                            Code = "ACS",
                            Name = "ACS"
                        },
                        new
                        {
                            Id = 8,
                            Code = "BRILL",
                            Name = "BRILL"
                        },
                        new
                        {
                            Id = 9,
                            Code = "NIHR",
                            Name = "NIHR"
                        },
                        new
                        {
                            Id = 10,
                            Code = "SANDBOX",
                            Name = "SANDBOX"
                        },
                        new
                        {
                            Id = 11,
                            Code = "TNFJOURNALS",
                            Name = "TNFJOURNALS"
                        },
                        new
                        {
                            Id = 12,
                            Code = "LSE",
                            Name = "LSE"
                        },
                        new
                        {
                            Id = 13,
                            Code = "MEDKNOW",
                            Name = "MEDKNOW"
                        },
                        new
                        {
                            Id = 14,
                            Code = "PLOS",
                            Name = "PLOS"
                        },
                        new
                        {
                            Id = 15,
                            Code = "INTELECCT",
                            Name = "Intellect"
                        });
                });

            modelBuilder.Entity("ImpactSupport.Api.TestCaseViewer.Data.ClientAlias", b =>
                {
                    b.Property<string>("Alias")
                        .HasColumnType("TEXT");

                    b.Property<int>("ClientId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Alias");

                    b.ToTable("ClientAliases", (string)null);

                    b.HasData(
                        new
                        {
                            Alias = "T & F",
                            ClientId = 3
                        },
                        new
                        {
                            Alias = "T&F",
                            ClientId = 3
                        },
                        new
                        {
                            Alias = "OxfordMed",
                            ClientId = 2
                        });
                });

            modelBuilder.Entity("ImpactSupport.Api.TestCaseViewer.Data.ClientSubBrand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClientId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ClientId", "Value")
                        .IsUnique();

                    b.ToTable("ClientSubBrands", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClientId = 5,
                            Value = "Thomson"
                        });
                });

            modelBuilder.Entity("ImpactSupport.Api.TestCaseViewer.Data.ContentType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Value")
                        .IsUnique();

                    b.ToTable("Types", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Value = "Journal"
                        },
                        new
                        {
                            Id = 2,
                            Value = "Book"
                        });
                });

            modelBuilder.Entity("ImpactSupport.Api.TestCaseViewer.Data.DtdType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Value")
                        .IsUnique();

                    b.ToTable("DtdType", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Value = "JATS"
                        },
                        new
                        {
                            Id = 2,
                            Value = "BITS"
                        },
                        new
                        {
                            Id = 3,
                            Value = "DOCBOOK"
                        });
                });

            modelBuilder.Entity("ImpactSupport.Api.TestCaseViewer.Data.MasterDevStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Value")
                        .IsUnique();

                    b.ToTable("MasterDevStatuses", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Value = "Fixed"
                        },
                        new
                        {
                            Id = 2,
                            Value = "Rejected"
                        },
                        new
                        {
                            Id = 3,
                            Value = "WIP"
                        },
                        new
                        {
                            Id = 4,
                            Value = "Open"
                        });
                });

            modelBuilder.Entity("ImpactSupport.Api.TestCaseViewer.Data.MasterIssueType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Value")
                        .IsUnique();

                    b.ToTable("MasterIssueTypes", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Value = "Bug"
                        },
                        new
                        {
                            Id = 2,
                            Value = "Change Request"
                        },
                        new
                        {
                            Id = 3,
                            Value = "Enhancement"
                        });
                });

            modelBuilder.Entity("ImpactSupport.Api.TestCaseViewer.Data.MasterModule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("MasterModules", (string)null);
                });

            modelBuilder.Entity("ImpactSupport.Api.TestCaseViewer.Data.MasterPreconditionRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Value")
                        .IsUnique();

                    b.ToTable("MasterPreconditionRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Value = "Author"
                        },
                        new
                        {
                            Id = 2,
                            Value = "PE"
                        },
                        new
                        {
                            Id = 3,
                            Value = "Collator"
                        },
                        new
                        {
                            Id = 4,
                            Value = "Editor"
                        });
                });

            modelBuilder.Entity("ImpactSupport.Api.TestCaseViewer.Data.MasterPreconditionRoleAlias", b =>
                {
                    b.Property<string>("Alias")
                        .HasColumnType("TEXT");

                    b.Property<int>("RoleId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Alias");

                    b.HasIndex("RoleId");

                    b.ToTable("MasterPreconditionRoleAliases", (string)null);

                    b.HasData(
                        new
                        {
                            Alias = "PE",
                            RoleId = 4
                        });
                });

            modelBuilder.Entity("ImpactSupport.Api.TestCaseViewer.Data.MasterQaStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Value")
                        .IsUnique();

                    b.ToTable("MasterQaStatuses", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Value = "Pass"
                        },
                        new
                        {
                            Id = 2,
                            Value = "Fail"
                        },
                        new
                        {
                            Id = 3,
                            Value = "Fixed"
                        },
                        new
                        {
                            Id = 4,
                            Value = "Rejected"
                        },
                        new
                        {
                            Id = 5,
                            Value = "WIP"
                        });
                });

            modelBuilder.Entity("ImpactSupport.Api.TestCaseViewer.Data.MasterTemplate", b =>
                {
                    b.Property<int>("MasterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("MasterActualResult")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("MasterClient")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("MasterCreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("MasterDeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("MasterDeletedBy")
                        .HasColumnType("TEXT");

                    b.Property<int?>("MasterDevStatus")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MasterDtdType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MasterExpectedResult")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("MasterIsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<bool>("MasterIsCollaborative")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("MasterIsSharedRole")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MasterIssueType")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MasterModules")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MasterOriginalRawId")
                        .HasColumnType("TEXT");

                    b.Property<int?>("MasterPreconditionRole")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MasterPreparedBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MasterPreparedDate")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("MasterQaStatus")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MasterRoleWorkflow")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MasterSourceRow")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MasterSourceSheet")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("MasterSubClient")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MasterTestData")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MasterTestId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MasterTestNo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("MasterType")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("MasterUpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("MasterUpdatedBy")
                        .HasColumnType("TEXT");

                    b.HasKey("MasterId");

                    b.HasIndex("MasterTestId")
                        .IsUnique();

                    b.ToTable("MasterTemplate", (string)null);
                });

            modelBuilder.Entity("ImpactSupport.Api.TestCaseViewer.Data.MasterTemplateClient", b =>
                {
                    b.Property<int>("MasterId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClientId")
                        .HasColumnType("INTEGER");

                    b.HasKey("MasterId", "ClientId");

                    b.ToTable("MasterTemplateClients", (string)null);
                });

            modelBuilder.Entity("ImpactSupport.Api.TestCaseViewer.Data.MasterTemplateEditHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("EditedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("EditedBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FieldName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("MasterId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NewValue")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OldValue")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MasterId", "EditedAt");

                    b.ToTable("MasterTemplateEditHistory", (string)null);
                });

            modelBuilder.Entity("ImpactSupport.Api.TestCaseViewer.Data.MasterTemplateRemark", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DevRemark")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("MasterId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("QaRemark")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RoundNumber")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MasterId");

                    b.ToTable("MasterTemplateRemarks", (string)null);
                });

            modelBuilder.Entity("ImpactSupport.Api.TestCaseViewer.Data.MasterTemplateTestingType", b =>
                {
                    b.Property<int>("MasterId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TestingTypeId")
                        .HasColumnType("INTEGER");

                    b.HasKey("MasterId", "TestingTypeId");

                    b.ToTable("MasterTemplateTestingTypes", (string)null);
                });

            modelBuilder.Entity("ImpactSupport.Api.TestCaseViewer.Data.MasterTestDetails", b =>
                {
                    b.Property<int>("MasterId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MasterDescription")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MasterTestSteps")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("MasterId");

                    b.ToTable("MasterTestDetails", (string)null);
                });

            modelBuilder.Entity("ImpactSupport.Api.TestCaseViewer.Data.MasterTestingType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Value")
                        .IsUnique();

                    b.ToTable("MasterTestingTypes", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Value = "Basic"
                        },
                        new
                        {
                            Id = 2,
                            Value = "Mock"
                        },
                        new
                        {
                            Id = 3,
                            Value = "Browser"
                        },
                        new
                        {
                            Id = 4,
                            Value = "Regression"
                        },
                        new
                        {
                            Id = 5,
                            Value = "Tomcat_Reg"
                        });
                });

            modelBuilder.Entity("ImpactSupport.Api.TestCaseViewer.Data.MasterTestingTypeAlias", b =>
                {
                    b.Property<string>("Alias")
                        .HasColumnType("TEXT");

                    b.Property<int>("TestingTypeId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Alias");

                    b.ToTable("MasterTestingTypeAliases", (string)null);

                    b.HasData(
                        new
                        {
                            Alias = "Tomcat_Regression",
                            TestingTypeId = 5
                        });
                });

            modelBuilder.Entity("ImpactSupport.Api.TestCaseViewer.Data.QaDashboardFileCache", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("DriveModifiedTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("FileId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FolderUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("LastDriveCheckedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("LastGoogleUpdateAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("LastLocalSyncAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("LastMetadataSyncedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("LastScannedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("LocalTsvPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PendingEditCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ReportType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ScanError")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ScanStatus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SyncError")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SyncStatus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ReportType", "FileId")
                        .IsUnique();

                    b.ToTable("QaDashboardFileCaches");
                });

            modelBuilder.Entity("ImpactSupport.Api.TestCaseViewer.Data.QaDashboardSheetCache", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DevRemarks")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DevStatus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("DriveModifiedTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("FailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FileCacheId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FileId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("FixedCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FutureDevelopmentCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LastGoogleUpdateAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("LastLocalSyncAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("LastMetadataSyncedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("LastRefreshedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Link")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LocalTsvPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Module")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("NotClearCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NotReplicateCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PassCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PendingEditCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PostponedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PurposeOfTesting")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RefreshError")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RefreshStatus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RejectedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Remarks")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RowsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("SheetGid")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SheetIndex")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SheetLink")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SheetName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SyncError")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SyncStatus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalTestCases")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WipCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("FileCacheId");

                    b.HasIndex("FileId", "SheetName")
                        .IsUnique();

                    b.ToTable("QaDashboardSheetCaches");
                });

            modelBuilder.Entity("ImpactSupport.Api.TestCaseViewer.Data.QaImportBatch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("CommittedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("ExistingSheets")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("NewSheets")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ResultMode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RowsAdded")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RowsError")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RowsSkipped")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RowsUpdated")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SheetsDetected")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UploadKind")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UploadedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("UploadedBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UploadKind", "Status");

                    b.ToTable("QaImportBatches");
                });

            modelBuilder.Entity("ImpactSupport.Api.TestCaseViewer.Data.QaImportBatchError", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ErrorMessage")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ImportBatchId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RawValue")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RowNumber")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ImportBatchId");

                    b.ToTable("QaImportBatchErrors");
                });

            modelBuilder.Entity("ImpactSupport.Api.TestCaseViewer.Data.QaImportBatchRow", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ImportBatchId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ImportBatchSheetId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ManualEditAction")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("ManualEditConflict")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("ManualEditLastEditedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ManualEditLastEditedBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalRawTestCaseId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RowJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SourceRowNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TestCaseId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ImportBatchSheetId");

                    b.HasIndex("ImportBatchId", "TestCaseId")
                        .IsUnique();

                    b.ToTable("QaImportBatchRows");
                });

            modelBuilder.Entity("ImpactSupport.Api.TestCaseViewer.Data.QaImportBatchSheet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConflictStatus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ImportBatchId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ModuleName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedSheetName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RowCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SelectedAction")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SheetName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ImportBatchId", "NormalizedSheetName")
                        .IsUnique();

                    b.ToTable("QaImportBatchSheets");
                });

            modelBuilder.Entity("ImpactSupport.Api.TestCaseViewer.Data.RefStyle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Value")
                        .IsUnique();

                    b.ToTable("RefStyles", (string)null);
                });

            modelBuilder.Entity("ImpactSupport.Api.TestCaseViewer.Data.RoleWorkflow", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Value")
                        .IsUnique();

                    b.ToTable("RoleWorkflows", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsDefault = true,
                            Value = "Author_Editor_Collator"
                        },
                        new
                        {
                            Id = 2,
                            IsDefault = false,
                            Value = "Editor_Author_Collator"
                        },
                        new
                        {
                            Id = 3,
                            IsDefault = false,
                            Value = "Author_Collator"
                        },
                        new
                        {
                            Id = 4,
                            IsDefault = false,
                            Value = "Editor_Collator"
                        });
                });

            modelBuilder.Entity("ImpactSupport.Api.TestCaseViewer.Data.TestCaseViewerUser", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MongoId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MongoId")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("TestCaseViewerUsers");
                });

            modelBuilder.Entity("ImpactSupport.Api.TestCaseViewer.Data.TestRunConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TestingName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TestingName")
                        .IsUnique();

                    b.ToTable("TestRunConfigs");
                });

            modelBuilder.Entity("ImpactSupport.Api.TestCaseViewer.Data.TestRunConfigFlag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ConfigId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FlagKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FlagValue")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ConfigId", "FlagKey")
                        .IsUnique();

                    b.ToTable("TestRunConfigFlags");
                });

            modelBuilder.Entity("ImpactSupport.Api.TestCaseViewer.Data.TestRunConfigTarget", b =>
                {
                    b.Property<int>("ConfigId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ModuleName")
                        .HasColumnType("TEXT");

                    b.HasKey("ConfigId", "ModuleName");

                    b.ToTable("TestRunConfigTargets");
                });

            modelBuilder.Entity("ImpactSupport.Api.TestCaseViewer.Data.TestRunConfigTestingType", b =>
                {
                    b.Property<int>("ConfigId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("ConfigId", "Value");

                    b.ToTable("TestRunConfigTestingTypes");
                });

            modelBuilder.Entity("ImpactSupport.Api.TestCaseViewer.Data.TestRunConfigWorkflowContext", b =>
                {
                    b.Property<int>("ConfigId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Client")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Domain")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MantisTicket")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RefStyle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleWorkflow")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TestingUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ConfigId");

                    b.ToTable("TestRunConfigWorkflowContexts");
                });

            modelBuilder.Entity("ImpactSupport.Api.TestCaseViewer.Data.TestRunExecution", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ConfigId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ExitCode")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FailureSummary")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("FinishedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("MantisTicket")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ModuleName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PlaywrightCommand")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PlaywrightTestsRef")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ReportPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RunKind")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TestCaseId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("TriggeredAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("TriggeredBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ConfigId", "Status");

                    b.ToTable("TestRunExecutions");
                });

            modelBuilder.Entity("ImpactSupport.Api.TestCaseViewer.Data.TestRunProgress", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ConfigId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("LastExecutionId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastModuleName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LastExecutionId");

                    b.HasIndex("ConfigId", "UserId")
                        .IsUnique();

                    b.ToTable("TestRunProgresses");
                });

            modelBuilder.Entity("ImpactSupport.Api.TestCaseViewer.Data.TestingDataResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MasterDevStatus")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MasterIssueType")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MasterQaStatus")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MasterTestId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TestingMetaResultId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TestingMetaResultId");

                    b.ToTable("TestingDataResults", (string)null);
                });

            modelBuilder.Entity("ImpactSupport.Api.TestCaseViewer.Data.TestingMetaResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("RunAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("RunBy")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RunThrough")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("TestingMetaResults", (string)null);
                });

            modelBuilder.Entity("ImpactSupport.Api.TestCaseViewer.Data.TestingMetaResultLink", b =>
                {
                    b.Property<int>("TestingMetaResultId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RoleId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TestingUrlId")
                        .HasColumnType("INTEGER");

                    b.HasKey("TestingMetaResultId", "RoleId");

                    b.ToTable("TestingMetaResultLinks", (string)null);
                });

            modelBuilder.Entity("ImpactSupport.Api.TestCaseViewer.Data.TestingMetaResultModuleStat", b =>
                {
                    b.Property<int>("TestingMetaResultId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MasterModuleId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FailCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PassCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("TestingMetaResultId", "MasterModuleId");

                    b.ToTable("TestingMetaResultModuleStats", (string)null);
                });

            modelBuilder.Entity("ImpactSupport.Api.TestCaseViewer.Data.TestingMetaResultTestingType", b =>
                {
                    b.Property<int>("TestingMetaResultId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TestingTypeId")
                        .HasColumnType("INTEGER");

                    b.HasKey("TestingMetaResultId", "TestingTypeId");

                    b.ToTable("TestingMetaResultTestingTypes", (string)null);
                });

            modelBuilder.Entity("ImpactSupport.Api.TestCaseViewer.Data.TestingUrl", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("UrlType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Value")
                        .IsUnique();

                    b.ToTable("TestingUrls", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            UrlType = "single",
                            Value = "author"
                        },
                        new
                        {
                            Id = 2,
                            UrlType = "single",
                            Value = "editor"
                        },
                        new
                        {
                            Id = 3,
                            UrlType = "single",
                            Value = "collator"
                        },
                        new
                        {
                            Id = 4,
                            UrlType = "multi_author",
                            Value = "shared_author"
                        },
                        new
                        {
                            Id = 5,
                            UrlType = "multi_author",
                            Value = "shared_editor"
                        },
                        new
                        {
                            Id = 6,
                            UrlType = "multi_author",
                            Value = "shared_collator"
                        });
                });

            modelBuilder.Entity("ImpactSupport.Api.TestCaseViewer.Data.TypeClientDtdMap", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClientId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DtdTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SubClientId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TypeId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("DtdTypeId");

                    b.HasIndex("SubClientId");

                    b.HasIndex("TypeId", "ClientId", "SubClientId")
                        .IsUnique();

                    b.ToTable("TypeClientDtdMap", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClientId = 7,
                            DtdTypeId = 1,
                            TypeId = 1
                        },
                        new
                        {
                            Id = 2,
                            ClientId = 8,
                            DtdTypeId = 1,
                            TypeId = 1
                        },
                        new
                        {
                            Id = 3,
                            ClientId = 15,
                            DtdTypeId = 1,
                            TypeId = 1
                        },
                        new
                        {
                            Id = 4,
                            ClientId = 5,
                            DtdTypeId = 1,
                            TypeId = 1
                        },
                        new
                        {
                            Id = 5,
                            ClientId = 13,
                            DtdTypeId = 1,
                            TypeId = 1
                        },
                        new
                        {
                            Id = 6,
                            ClientId = 9,
                            DtdTypeId = 1,
                            TypeId = 1
                        },
                        new
                        {
                            Id = 7,
                            ClientId = 4,
                            DtdTypeId = 1,
                            TypeId = 1
                        },
                        new
                        {
                            Id = 8,
                            ClientId = 14,
                            DtdTypeId = 1,
                            TypeId = 1
                        },
                        new
                        {
                            Id = 9,
                            ClientId = 10,
                            DtdTypeId = 1,
                            TypeId = 1
                        },
                        new
                        {
                            Id = 10,
                            ClientId = 11,
                            DtdTypeId = 1,
                            TypeId = 1
                        },
                        new
                        {
                            Id = 11,
                            ClientId = 5,
                            DtdTypeId = 1,
                            SubClientId = 1,
                            TypeId = 1
                        },
                        new
                        {
                            Id = 12,
                            ClientId = 12,
                            DtdTypeId = 2,
                            TypeId = 2
                        },
                        new
                        {
                            Id = 13,
                            ClientId = 6,
                            DtdTypeId = 2,
                            TypeId = 2
                        },
                        new
                        {
                            Id = 14,
                            ClientId = 1,
                            DtdTypeId = 2,
                            TypeId = 2
                        },
                        new
                        {
                            Id = 15,
                            ClientId = 2,
                            DtdTypeId = 2,
                            TypeId = 2
                        },
                        new
                        {
                            Id = 16,
                            ClientId = 3,
                            DtdTypeId = 2,
                            TypeId = 2
                        });
                });

            modelBuilder.Entity("ImpactSupport.Api.Support.Data.SupportMessage", b =>
                {
                    b.HasOne("ImpactSupport.Api.Support.Data.SupportSession", "SupportSession")
                        .WithMany("Messages")
                        .HasForeignKey("SupportSessionId")
                        .HasPrincipalKey("SupportSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SupportSession");
                });

            modelBuilder.Entity("ImpactSupport.Api.TestCaseViewer.Data.ClientSubBrand", b =>
                {
                    b.HasOne("ImpactSupport.Api.TestCaseViewer.Data.Client", null)
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ImpactSupport.Api.TestCaseViewer.Data.MasterPreconditionRoleAlias", b =>
                {
                    b.HasOne("ImpactSupport.Api.TestCaseViewer.Data.MasterPreconditionRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ImpactSupport.Api.TestCaseViewer.Data.MasterTemplateClient", b =>
                {
                    b.HasOne("ImpactSupport.Api.TestCaseViewer.Data.MasterTemplate", "MasterTemplate")
                        .WithMany("Clients")
                        .HasForeignKey("MasterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MasterTemplate");
                });

            modelBuilder.Entity("ImpactSupport.Api.TestCaseViewer.Data.MasterTemplateEditHistory", b =>
                {
                    b.HasOne("ImpactSupport.Api.TestCaseViewer.Data.MasterTemplate", "MasterTemplate")
                        .WithMany("EditHistory")
                        .HasForeignKey("MasterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MasterTemplate");
                });

            modelBuilder.Entity("ImpactSupport.Api.TestCaseViewer.Data.MasterTemplateRemark", b =>
                {
                    b.HasOne("ImpactSupport.Api.TestCaseViewer.Data.MasterTemplate", "MasterTemplate")
                        .WithMany("Remarks")
                        .HasForeignKey("MasterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MasterTemplate");
                });

            modelBuilder.Entity("ImpactSupport.Api.TestCaseViewer.Data.MasterTemplateTestingType", b =>
                {
                    b.HasOne("ImpactSupport.Api.TestCaseViewer.Data.MasterTemplate", "MasterTemplate")
                        .WithMany("TestingTypes")
                        .HasForeignKey("MasterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MasterTemplate");
                });

            modelBuilder.Entity("ImpactSupport.Api.TestCaseViewer.Data.MasterTestDetails", b =>
                {
                    b.HasOne("ImpactSupport.Api.TestCaseViewer.Data.MasterTemplate", "MasterTemplate")
                        .WithOne("Details")
                        .HasForeignKey("ImpactSupport.Api.TestCaseViewer.Data.MasterTestDetails", "MasterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MasterTemplate");
                });

            modelBuilder.Entity("ImpactSupport.Api.TestCaseViewer.Data.QaDashboardSheetCache", b =>
                {
                    b.HasOne("ImpactSupport.Api.TestCaseViewer.Data.QaDashboardFileCache", "FileCache")
                        .WithMany("Sheets")
                        .HasForeignKey("FileCacheId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FileCache");
                });

            modelBuilder.Entity("ImpactSupport.Api.TestCaseViewer.Data.QaImportBatchError", b =>
                {
                    b.HasOne("ImpactSupport.Api.TestCaseViewer.Data.QaImportBatch", "ImportBatch")
                        .WithMany("Errors")
                        .HasForeignKey("ImportBatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ImportBatch");
                });

            modelBuilder.Entity("ImpactSupport.Api.TestCaseViewer.Data.QaImportBatchRow", b =>
                {
                    b.HasOne("ImpactSupport.Api.TestCaseViewer.Data.QaImportBatch", "ImportBatch")
                        .WithMany("Rows")
                        .HasForeignKey("ImportBatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ImpactSupport.Api.TestCaseViewer.Data.QaImportBatchSheet", "ImportBatchSheet")
                        .WithMany("Rows")
                        .HasForeignKey("ImportBatchSheetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ImportBatch");

                    b.Navigation("ImportBatchSheet");
                });

            modelBuilder.Entity("ImpactSupport.Api.TestCaseViewer.Data.QaImportBatchSheet", b =>
                {
                    b.HasOne("ImpactSupport.Api.TestCaseViewer.Data.QaImportBatch", "ImportBatch")
                        .WithMany("Sheets")
                        .HasForeignKey("ImportBatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ImportBatch");
                });

            modelBuilder.Entity("ImpactSupport.Api.TestCaseViewer.Data.TestRunConfigFlag", b =>
                {
                    b.HasOne("ImpactSupport.Api.TestCaseViewer.Data.TestRunConfig", "Config")
                        .WithMany("Flags")
                        .HasForeignKey("ConfigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Config");
                });

            modelBuilder.Entity("ImpactSupport.Api.TestCaseViewer.Data.TestRunConfigTarget", b =>
                {
                    b.HasOne("ImpactSupport.Api.TestCaseViewer.Data.TestRunConfig", "Config")
                        .WithMany("Targets")
                        .HasForeignKey("ConfigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Config");
                });

            modelBuilder.Entity("ImpactSupport.Api.TestCaseViewer.Data.TestRunConfigTestingType", b =>
                {
                    b.HasOne("ImpactSupport.Api.TestCaseViewer.Data.TestRunConfig", "Config")
                        .WithMany("TestingTypes")
                        .HasForeignKey("ConfigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Config");
                });

            modelBuilder.Entity("ImpactSupport.Api.TestCaseViewer.Data.TestRunConfigWorkflowContext", b =>
                {
                    b.HasOne("ImpactSupport.Api.TestCaseViewer.Data.TestRunConfig", "Config")
                        .WithOne("WorkflowContext")
                        .HasForeignKey("ImpactSupport.Api.TestCaseViewer.Data.TestRunConfigWorkflowContext", "ConfigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Config");
                });

            modelBuilder.Entity("ImpactSupport.Api.TestCaseViewer.Data.TestRunExecution", b =>
                {
                    b.HasOne("ImpactSupport.Api.TestCaseViewer.Data.TestRunConfig", "Config")
                        .WithMany("Executions")
                        .HasForeignKey("ConfigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Config");
                });

            modelBuilder.Entity("ImpactSupport.Api.TestCaseViewer.Data.TestRunProgress", b =>
                {
                    b.HasOne("ImpactSupport.Api.TestCaseViewer.Data.TestRunConfig", "Config")
                        .WithMany()
                        .HasForeignKey("ConfigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ImpactSupport.Api.TestCaseViewer.Data.TestRunExecution", "LastExecution")
                        .WithMany()
                        .HasForeignKey("LastExecutionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Config");

                    b.Navigation("LastExecution");
                });

            modelBuilder.Entity("ImpactSupport.Api.TestCaseViewer.Data.TestingDataResult", b =>
                {
                    b.HasOne("ImpactSupport.Api.TestCaseViewer.Data.TestingMetaResult", "TestingMetaResult")
                        .WithMany("DataResults")
                        .HasForeignKey("TestingMetaResultId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TestingMetaResult");
                });

            modelBuilder.Entity("ImpactSupport.Api.TestCaseViewer.Data.TestingMetaResultModuleStat", b =>
                {
                    b.HasOne("ImpactSupport.Api.TestCaseViewer.Data.TestingMetaResult", "TestingMetaResult")
                        .WithMany("ModuleStats")
                        .HasForeignKey("TestingMetaResultId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TestingMetaResult");
                });

            modelBuilder.Entity("ImpactSupport.Api.TestCaseViewer.Data.TypeClientDtdMap", b =>
                {
                    b.HasOne("ImpactSupport.Api.TestCaseViewer.Data.Client", null)
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ImpactSupport.Api.TestCaseViewer.Data.DtdType", null)
                        .WithMany()
                        .HasForeignKey("DtdTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ImpactSupport.Api.TestCaseViewer.Data.ClientSubBrand", null)
                        .WithMany()
                        .HasForeignKey("SubClientId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ImpactSupport.Api.TestCaseViewer.Data.ContentType", null)
                        .WithMany()
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ImpactSupport.Api.Support.Data.SupportSession", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("ImpactSupport.Api.TestCaseViewer.Data.MasterTemplate", b =>
                {
                    b.Navigation("Clients");

                    b.Navigation("Details");

                    b.Navigation("EditHistory");

                    b.Navigation("Remarks");

                    b.Navigation("TestingTypes");
                });

            modelBuilder.Entity("ImpactSupport.Api.TestCaseViewer.Data.QaDashboardFileCache", b =>
                {
                    b.Navigation("Sheets");
                });

            modelBuilder.Entity("ImpactSupport.Api.TestCaseViewer.Data.QaImportBatch", b =>
                {
                    b.Navigation("Errors");

                    b.Navigation("Rows");

                    b.Navigation("Sheets");
                });

            modelBuilder.Entity("ImpactSupport.Api.TestCaseViewer.Data.QaImportBatchSheet", b =>
                {
                    b.Navigation("Rows");
                });

            modelBuilder.Entity("ImpactSupport.Api.TestCaseViewer.Data.TestRunConfig", b =>
                {
                    b.Navigation("Executions");

                    b.Navigation("Flags");

                    b.Navigation("Targets");

                    b.Navigation("TestingTypes");

                    b.Navigation("WorkflowContext");
                });

            modelBuilder.Entity("ImpactSupport.Api.TestCaseViewer.Data.TestingMetaResult", b =>
                {
                    b.Navigation("DataResults");

                    b.Navigation("ModuleStats");
                });
#pragma warning restore 612, 618
        }
    }
}
